# Generated by Django 3.2 on 2021-12-15 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionDetailParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('solution_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.solutiondetail')),
            ],
        ),
    ]
