# Generated by Django 3.2 on 2021-12-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_continentlocation_countryaddress_countrylocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='countryAddress',
        ),
    ]
